function Hd = getFilter
%GETFILTER Returns a discrete-time filter System object.

% MATLAB Code
% Generated by MATLAB(R) 9.3 and DSP System Toolbox 9.5.
% Generated on: 08-Apr-2018 21:52:28

Fpass = 10000;   % Passband Frequency
Fstop = 20000;   % Stopband Frequency
Apass = 5;       % Passband Ripple (dB)
Astop = 50;      % Stopband Attenuation (dB)
Fs    = 100000;  % Sampling Frequency

h = fdesign.lowpass('fp,fst,ap,ast', Fpass, Fstop, Apass, Astop, Fs);

Hd = design(h, 'butter', ...
    'MatchExactly', 'passband', ...
    'SystemObject', true);


