function Hd = getFilter4
%GETFILTER Returns a discrete-time filter System object.

% MATLAB Code
% Generated by MATLAB(R) 9.3 and DSP System Toolbox 9.5.
% Generated on: 08-Apr-2018 21:56:17

Fstop1 = 15000;   % First Stopband Frequency
Fpass1 = 20000;   % First Passband Frequency
Fpass2 = 30000;   % Second Passband Frequency
Fstop2 = 35000;   % Second Stopband Frequency
Astop1 = 50;      % First Stopband Attenuation (dB)
Apass  = 5;       % Passband Ripple (dB)
Astop2 = 50;      % Second Stopband Attenuation (dB)
Fs     = 100000;  % Sampling Frequency

h = fdesign.bandpass('fst1,fp1,fp2,fst2,ast1,ap,ast2', Fstop1, Fpass1, ...
    Fpass2, Fstop2, Astop1, Apass, Astop2, Fs);

Hd = design(h, 'ellip', ...
    'MatchExactly', 'passband', ...
    'SystemObject', true);


