function Hd = getFilter3
%GETFILTER Returns a discrete-time filter System object.

% MATLAB Code
% Generated by MATLAB(R) 9.3 and DSP System Toolbox 9.5.
% Generated on: 08-Apr-2018 21:55:54

Fpass1 = 5000;    % First Passband Frequency
Fstop1 = 15000;   % First Stopband Frequency
Fstop2 = 35000;   % Second Stopband Frequency
Fpass2 = 45000;   % Second Passband Frequency
Apass1 = 5;       % First Passband Ripple (dB)
Astop  = 50;      % Stopband Attenuation (dB)
Apass2 = 1;       % Second Passband Ripple (dB)
Fs     = 100000;  % Sampling Frequency

h = fdesign.bandstop('fp1,fst1,fst2,fp2,ap1,ast,ap2', Fpass1, Fstop1, ...
    Fstop2, Fpass2, Apass1, Astop, Apass2, Fs);

Hd = design(h, 'cheby2', ...
    'MatchExactly', 'stopband', ...
    'SystemObject', true);


